# Generated by Django 5.2.14 on 2026-05-25 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'grupo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='conversationapp.grupo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mensagens',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_usuario', to='conversationapp.grupo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_grupo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_grupos',
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='participantes',
            field=models.ManyToManyField(related_name='grupos_conversa', through='conversationapp.UsuarioGrupo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='usuariogrupo',
            constraint=models.UniqueConstraint(fields=('user', 'grupo'), name='uniq_user_grupo'),
        ),
    ]
