# Generated by Django 5.2.14 on 2026-05-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversationapp', '0002_perfil_amizade'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='theme',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
